# Generated by Django 4.2 on 2024-03-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveSmallIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'content'), ('model', 'postmodel')), models.Q(('app_label', 'content'), ('model', 'storymodel')), models.Q(('app_label', 'user'), ('model', 'userprofilemodel')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='previews', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preview',
                'verbose_name_plural': 'Previews',
            },
        ),
    ]
