# Generated by Django 4.2 on 2024-03-05 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previewmodel',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
