# Generated by Django 4.2 on 2024-03-02 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('object_id', models.PositiveSmallIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(limit_choices_to={'content__in': ['post', 'story']}, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='contenttypes.contenttype', verbose_name='Content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveSmallIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(limit_choices_to={'content__in': ['post', 'story'], 'user_activity__in': ['comment']}, on_delete=django.db.models.deletion.PROTECT, related_name='like', to='contenttypes.contenttype', verbose_name='Content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
