# Generated by Django 4.2 on 2024-03-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'content'), ('model', 'postmodel')), models.Q(('app_label', 'content'), ('model', 'storymodel')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'content'), ('model', 'postmodel')), models.Q(('app_label', 'content'), ('model', 'storymodel')), models.Q(('app_label', 'user_activity'), ('model', 'commentmodel')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='like', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
    ]
