# Generated by Django 4.2 on 2024-03-02 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('relation_type', models.CharField(choices=[('follower', 'Follower'), ('following', 'Following'), ('blocked', 'Blocked')], max_length=15, verbose_name='Relation type')),
                ('related_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_relations', to=settings.AUTH_USER_MODEL, verbose_name='Relate with')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_relations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Relation',
                'verbose_name_plural': 'User Relations',
                'unique_together': {('user', 'related_with', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='%Y/%m', verbose_name='Profile picture')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profile',
            },
        ),
        migrations.CreateModel(
            name='CloseFriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('close_friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_friends_relations', to=settings.AUTH_USER_MODEL, verbose_name='Close friend')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_friends', to='user.userrelationmodel', verbose_name='User relation')),
            ],
            options={
                'verbose_name': 'Close friend',
                'verbose_name_plural': 'Close friend',
            },
        ),
    ]
