# Generated by Django 4.2 on 2024-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
    ]
