# Generated by Django 4.2 on 2024-03-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('object_id', models.PositiveSmallIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'content'), ('model', 'postmodel')), models.Q(('app_label', 'content'), ('model', 'storymodel')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'unique_together': {('content_type', 'object_id', 'title')},
            },
        ),
    ]
